### ISSUE TITLE
Generator hangs on (node:22696) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by seanrowe** [da1nerd/generator-react-app-electron#8]
After installing the generator in Windows, if I try to use it, after I enter in the name of the project I see this deprecation warning and then it hangs.

(node:22696) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**Comment by neutrinog** [comment]
What version of node are you using?
